#!/usr/bin/env python

__author__ = "John Kirkham <kirkhamj@janelia.hhmi.org>"
__date__ = "$Aug 03 2015 20:07:15 EDT$"


if __name__ == "__main__":
    import sys
    from startup_nanshe_workflow import main
    sys.exit(main(*sys.argv))
