machine:
  services:
    - docker

checkout:
  post:
    - git submodule update --init --recursive

dependencies:
  override:
    - docker info

test:
  override:
    - docker build -t nanshe/nanshe_workflow .
